# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24958239dc480abae92769220bdd818b63412e48df9150bcfca25a865e1d42c21a94d15bab5596ac8f1f56fbea3b024403592be13f109e04be11a536928b13d5

test:
  secret_key_base: 78b01128eaec4c1588e04b145699797c8156dd06d16c1281c9a49c3efeaacdd20aa88f41baa8ee45517aeae8d763202fdd52d045727509b47f1ccb860d7a9056

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
